export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const LOAD_LISTINGS_SUCCESS = 'LOAD_LISTINGS_SUCCESS';

export const LOAD_TRANSACTIONS_SUCCESS = 'LOAD_TRANSACTIONS_SUCCESS';

export const LOAD_REVIEWS_SUCCESS = 'LOAD_REVIEWS_SUCCESS';